# Generated by Django 3.1.10 on 2021-05-11 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='description',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('games', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='games.game')),
            ],
        ),
    ]
